[workspace]
members = [
        "usbredirparser-sys",
        "usbredirparser",
        "usbredirhost-sys",
        "usbredirhost",
]

[patch.crates-io]
libusb1-sys = { path = "/home/elmarco/src/rusb/libusb1-sys" }
rusb = { path = "/home/elmarco/src/rusb" }
