[workspace]
members = [
        "usbredirparser-sys",
        "usbredirparser",
        "usbredirhost-sys",
        "usbredirhost",
        "usbredir-helper",
]

[patch.crates-io]
libusb1-sys = { git = "https://github.com/a1ien/rusb.git" }
rusb = { git = "https://github.com/a1ien/rusb.git" }
