[package]
name = "usbredir-helper"
version = "0.3.0"
edition = "2021"

[dependencies]
zbus = { version = "5.3" }
zbus_polkit = { version = "5.0" }
async-std = { version = "1.13", features = [ "attributes" ] }
event-listener = "5.4"
