[package]
name = "usbredir-helper"
version = "0.2.0"
edition = "2018"

[dependencies]
zbus = { version = "4.2.2" }
zbus_polkit = { version = "4.0.0" }
async-std = { version = "1.12.0", features = [ "attributes" ] }
event-listener = "5.3.0"
