[package]
name = "usbredir-helper"
version = "0.1.0"
edition = "2018"

[dependencies]
zbus = { version = "2.3.2" }
zbus_polkit = { version = "2.0.2" }
async-std = { version = "1.9.0", features = [ "attributes" ] }
